[package]
name = "genetic_algorithms"
version = "0.1.0"
authors = ["Diego Carrillo <dailexgo@gmail.com>"]

[lib]
name = "genetic_algorithms"
path =  "src/lib.rs"

[[bin]]
name = "genetic_algorithms_bin"
path = "src/main.rs"

[dependencies]
rand = "0.3.15"
config = "*"
